/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ridotoji Pham
 */
public class FrmChinh extends javax.swing.JFrame {

    /**
     * Creates new form FrmChinh
     */
    public FrmChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnThuChi = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnhethong = new javax.swing.JMenu();
        mnuDonHang = new javax.swing.JMenuItem();
        MnuNhanVien = new javax.swing.JMenuItem();
        MnuKhachHang = new javax.swing.JMenuItem();
        btnDangxuat = new javax.swing.JMenuItem();
        mngioithieu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1479923089_Shopping_cart.png"))); // NOI18N
        jButton1.setText("Bán hàng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 150, 160, 53);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nhap hang.png"))); // NOI18N
        jButton3.setText("Nhập hàng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 150, 160, 53);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hang hoa.png"))); // NOI18N
        jButton2.setText("Hàng hóa");
        jButton2.setPreferredSize(new java.awt.Dimension(135, 53));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 300, 160, 53);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bao hanh.png"))); // NOI18N
        jButton4.setText("Bảo hành");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(100, 220, 160, 53);

        btnThuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thu chi.png"))); // NOI18N
        btnThuChi.setText("Thu-chi");
        btnThuChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuChiActionPerformed(evt);
            }
        });
        getContentPane().add(btnThuChi);
        btnThuChi.setBounds(280, 220, 160, 53);

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nhan vien.png"))); // NOI18N
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        getContentPane().add(btnNhanVien);
        btnNhanVien.setBounds(470, 220, 160, 53);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thong ke.png"))); // NOI18N
        jButton7.setText("Thống kê");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(280, 300, 160, 53);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Store.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 128, 128);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PHẦN MỀM QUẢN LÝ BÁN HÀNG");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(148, 50, 226, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phanmemquanlybanhang@gmail.com");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(148, 78, 177, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hinh nen.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 790, 440);

        mnhethong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HeThong.png"))); // NOI18N
        mnhethong.setText("Hệ thống");

        mnuDonHang.setText("Bảng Đơn Hàng");
        mnuDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDonHangActionPerformed(evt);
            }
        });
        mnhethong.add(mnuDonHang);

        MnuNhanVien.setText("Bảng Nhân Viên");
        MnuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuNhanVienActionPerformed(evt);
            }
        });
        mnhethong.add(MnuNhanVien);

        MnuKhachHang.setText("Bảng Khách Hàng");
        MnuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuKhachHangActionPerformed(evt);
            }
        });
        mnhethong.add(MnuKhachHang);

        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });
        mnhethong.add(btnDangxuat);

        jMenuBar1.add(mnhethong);

        mngioithieu.setText("Giới Thiệu");
        mngioithieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mngioithieuMouseClicked(evt);
            }
        });
        mngioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngioithieuActionPerformed(evt);
            }
        });
        jMenuBar1.add(mngioithieu);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuNhanVienActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MnuNhanVienActionPerformed

    private void MnuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuKhachHangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MnuKhachHangActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        // TODO add your handling code here:
                frmDangNhap frm = new frmDangNhap();
               frm.show();
                       this.dispose();


    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void mngioithieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mngioithieuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mngioithieuMouseClicked

    private void mngioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngioithieuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mngioithieuActionPerformed

    private void mnuDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDonHangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuDonHangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmBanHang frm = new FrmBanHang();
        frm.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        FrmNhanVien frm = new FrmNhanVien();
        frm.show();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FrmNhapHang frm = new FrmNhapHang();
        frm.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FrmBaoHanh frm = new FrmBaoHanh();
        frm.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnThuChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuChiActionPerformed
        // TODO add your handling code here:
        FrmThuChi frm = new FrmThuChi();
        frm.show();
    }//GEN-LAST:event_btnThuChiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FrmHangHoa frm = new FrmHangHoa();
        frm.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        FrmThongKe frm = new FrmThongKe();
        frm.show();
                
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         if(frmDangNhap.quyen == 1){
            ThongBao("Tôi Là Quản Lý", "Thông báo quyền", 2);
         }else if(frmDangNhap.quyen == 2){
            ThongBao("Tôi là Nhân Viên", "Thông báo quyền", 2);
            btnNhanVien.setEnabled(false);
            btnThuChi.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened
private void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) {
        JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
                tieuDeThongBao, icon);
      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuKhachHang;
    private javax.swing.JMenuItem MnuNhanVien;
    private javax.swing.JMenuItem btnDangxuat;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnThuChi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mngioithieu;
    private javax.swing.JMenu mnhethong;
    private javax.swing.JMenuItem mnuDonHang;
    // End of variables declaration//GEN-END:variables
}
