/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import BLL.ComboboxBLL;
import BLL.HangHoaSPBLL;
import BLL.LoaiSanPhamBLL;
import DAL.ConnectionDB;
import DAL.HangHoaSPDAL;
import DTO.HangHoaSPDTO;
import DTO.LoaiSanPhamDTO;
import FormNho.*;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JTable;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.awt.print.*;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Ridotoji Pham
 */
public class FrmHangHoa extends javax.swing.JFrame {

    /**
     * Creates new form FrmHangHoa
     */
    public FrmHangHoa() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HangHoa = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnthemdonhang = new javax.swing.JButton();
        btnsuadonhang = new javax.swing.JButton();
        btnxoadonhang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldonhang = new javax.swing.JTable();
        btnxuat = new javax.swing.JButton();
        lbltimkiem = new javax.swing.JLabel();
        cbbLoaiHanghoa = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cbbNhomHang = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltonkhoHangHoa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnthemdonhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Them.png"))); // NOI18N
        btnthemdonhang.setText("Thêm");
        btnthemdonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnthemdonhangMouseClicked(evt);
            }
        });

        btnsuadonhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sua.png"))); // NOI18N
        btnsuadonhang.setText("Sửa");
        btnsuadonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsuadonhangMouseClicked(evt);
            }
        });

        btnxoadonhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        btnxoadonhang.setText("Xóa");
        btnxoadonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnxoadonhangMouseClicked(evt);
            }
        });
        btnxoadonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoadonhangActionPerformed(evt);
            }
        });

        txttimkiem.setToolTipText("");
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        tbldonhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Đơn hàng", "Đơn vị", "Số lượng", "Giá mua", "Giá bán", "Bảo hành"
            }
        ));
        tbldonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldonhangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldonhang);

        btnxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xuat.png"))); // NOI18N
        btnxuat.setText("Xuất");
        btnxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatActionPerformed(evt);
            }
        });

        lbltimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        lbltimkiem.setText("Tìm kiếm:");
        lbltimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbltimkiemMouseClicked(evt);
            }
        });

        cbbLoaiHanghoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPhone", "Item 2", "Item 3", "Item 4" }));
        cbbLoaiHanghoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoaiHanghoaItemStateChanged(evt);
            }
        });
        cbbLoaiHanghoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbLoaiHanghoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbLoaiHanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnthemdonhang)
                        .addGap(18, 18, 18)
                        .addComponent(btnsuadonhang)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoadonhang)
                        .addGap(29, 29, 29)
                        .addComponent(lbltimkiem)
                        .addGap(18, 18, 18)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxuat)
                        .addGap(9, 9, 9))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnthemdonhang)
                        .addComponent(btnsuadonhang)
                        .addComponent(btnxoadonhang)
                        .addComponent(lbltimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnxuat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbLoaiHanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        HangHoa.addTab("Hàng Hóa", jPanel1);

        cbbNhomHang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhóm Hàng", "--------", "Item 2", "Item 3", "Item 4" }));
        cbbNhomHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbNhomHangItemStateChanged(evt);
            }
        });
        cbbNhomHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbNhomHangMouseClicked(evt);
            }
        });

        tbltonkhoHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên hàng", "Đơn vị", "Số lượng", "Mua vào", "Trị giá"
            }
        ));
        jScrollPane3.setViewportView(tbltonkhoHangHoa);

        jLabel2.setText("Số lượng :");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Trị giá :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbbNhomHang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbNhomHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(218, 218, 218)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HangHoa.addTab("Tồn kho", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HangHoa)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemdonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthemdonhangMouseClicked
        // TODO add your handling code here:
           FrmThemHangHoa frm = new FrmThemHangHoa();
           frm.show();
       ResultSet rs = HangHoaSPBLL.LayTatCaDonhang();
        HangHoaSPBLL.DoDuLieuVaoJTableDonHang(rs, tbldonhang);
    }//GEN-LAST:event_btnthemdonhangMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnsuadonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsuadonhangMouseClicked
        // TODO add your handling code here:
          FrmSuaHangHoa frm = new FrmSuaHangHoa();
                    frm.show();
         ResultSet rs = HangHoaSPBLL.LayTatCaDonhang();
        HangHoaSPBLL.DoDuLieuVaoJTableDonHang(rs, tbldonhang);
    }//GEN-LAST:event_btnsuadonhangMouseClicked

    private void btnxoadonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxoadonhangMouseClicked
        // TODO add your handling code here:
  
    }//GEN-LAST:event_btnxoadonhangMouseClicked

    private void lbltimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltimkiemMouseClicked
        // TODO add your handling code here:
          String tuKhoa = txttimkiem.getText();
       //Kết quả của tìm theo từ khóa ResultSet
        ResultSet rs = HangHoaSPBLL.LaySanPhamTheoTuKhoa(tuKhoa);
       //gọi hàm đổ dữ liệu sau khi tìm kiếm vào Table
      HangHoaSPBLL.DoDuLieuVaoJTableDonHang(rs, tbldonhang);
    }//GEN-LAST:event_lbltimkiemMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          ResultSet rs = HangHoaSPBLL.LayTatCaDonhang();
         HangHoaSPBLL.DoDuLieuVaoJTableDonHang(rs,tbldonhang);
         
        ResultSet rs1 = HangHoaSPBLL.LayTatCaLSP();
       ComboboxBLL.LoadDuLieuCombobox(rs1, cbbNhomHang, "TenLoaiSanPham", "MaLoaiSanPham");
        
       ResultSet rs2 = HangHoaSPBLL.LayTatCaLSP();
        ComboboxBLL.LoadDuLieuCombobox(rs2, cbbLoaiHanghoa, "TenLoaiSanPham", "MaLoaiSanPham");
         
          ResultSet rs3 = HangHoaSPBLL.Laybangtonkho();
        HangHoaSPBLL.DoDuLieuVaoJTableBangtonkho(rs3,tbltonkhoHangHoa);
       
    }//GEN-LAST:event_formWindowOpened

    private void cbbNhomHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbNhomHangMouseClicked
      
    }//GEN-LAST:event_cbbNhomHangMouseClicked

    private void cbbNhomHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbNhomHangItemStateChanged
    if(evt.getStateChange() == 1){
            String maLoaiSPDuocChon = ComboboxBLL.getSelectedItemID(cbbNhomHang);
        ResultSet rs = HangHoaSPBLL.LaySanPhamTheoTenSanPham(maLoaiSPDuocChon,maLoaiSPDuocChon);
            HangHoaSPBLL.DoDuLieuVaoJTableDonHang(rs, tbltonkhoHangHoa);
        }
    }//GEN-LAST:event_cbbNhomHangItemStateChanged

    private void tbldonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldonhangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbldonhangMouseClicked

    private void cbbLoaiHanghoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbLoaiHanghoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiHanghoaMouseClicked
 
    private void btnxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatActionPerformed
        // TODO add your handling code here:
        ResultSet rs = HangHoaSPBLL.LayTatCaDonhang();
        HangHoaSPBLL.DoDuLieuVaoJTableDonHang(rs, tbldonhang);
    }//GEN-LAST:event_btnxuatActionPerformed

    private void cbbLoaiHanghoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoaiHanghoaItemStateChanged
 if(evt.getStateChange() == 1){
            String maLoaiSPDuocChon = ComboboxBLL.getSelectedItemID(cbbLoaiHanghoa);
            ResultSet rs = HangHoaSPBLL.LaySanPhamTheoMaLoaiSP(maLoaiSPDuocChon);
            HangHoaSPBLL.DoDuLieuVaoJTableDonHang(rs, tbldonhang);
        }
    }//GEN-LAST:event_cbbLoaiHanghoaItemStateChanged

    private void btnxoadonhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoadonhangActionPerformed
        // TODO add your handling code here:
                int[] cacViTriDuocChon = tbldonhang.getSelectedRows();
           for(int i = 0; i < cacViTriDuocChon.length; i++){
    String MaLoaiCanXoa = tbldonhang.getValueAt(cacViTriDuocChon[i], 0).toString() ;
     //Gọi hàm xóa ở tầng xử lý
            HangHoaSPBLL.XoaDonHang(MaLoaiCanXoa);
         }
           ResultSet rs = HangHoaSPBLL.LayTatCaDonhang();
        //Đọc lại dữ liệu và đổ lại dữ liệu
       HangHoaSPBLL.DoDuLieuVaoJTableDonHang(rs, tbldonhang);  
    }//GEN-LAST:event_btnxoadonhangActionPerformed

    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        // TODO add your handling code here:
             String tuKhoa = txttimkiem.getText();
       //Kết quả của tìm theo từ khóa ResultSet
        ResultSet rs = HangHoaSPBLL.LaySanPhamTheoTuKhoa(tuKhoa);
       //gọi hàm đổ dữ liệu sau khi tìm kiếm vào Table
      HangHoaSPBLL.DoDuLieuVaoJTableDonHang(rs, tbldonhang);
    }//GEN-LAST:event_txttimkiemKeyReleased
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHangHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane HangHoa;
    private javax.swing.JButton btnsuadonhang;
    private javax.swing.JButton btnthemdonhang;
    private javax.swing.JButton btnxoadonhang;
    private javax.swing.JButton btnxuat;
    private javax.swing.JComboBox<String> cbbLoaiHanghoa;
    private javax.swing.JComboBox cbbNhomHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbltimkiem;
    private javax.swing.JTable tbldonhang;
    private javax.swing.JTable tbltonkhoHangHoa;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables

}

