/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;
import BLL.NhanVienBLL;
import BLL.QuyenBLL;
import FormNho.*;
import java.sql.ResultSet;
/**
 *
 * @author Ridotoji Pham
 */
public class FrmNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form FrmNhanVien
     */
    public FrmNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NhanVien = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblquyen = new javax.swing.JTable();
        btnthemnhanvien = new javax.swing.JButton();
        btnsuanhanvien = new javax.swing.JButton();
        btnxoanhanvien = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblnhanvien = new javax.swing.JTable();
        txttimkiem = new javax.swing.JTextField();
        lbltimkiem = new javax.swing.JLabel();
        btnhienhethong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblquyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {""},
                {null},
                {null}
            },
            new String [] {
                "Tên nhóm"
            }
        ));
        jScrollPane1.setViewportView(tblquyen);

        btnthemnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Them.png"))); // NOI18N
        btnthemnhanvien.setText("Thêm");
        btnthemnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemnhanvienActionPerformed(evt);
            }
        });

        btnsuanhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sua.png"))); // NOI18N
        btnsuanhanvien.setText("Sửa");
        btnsuanhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuanhanvienActionPerformed(evt);
            }
        });

        btnxoanhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xoa.png"))); // NOI18N
        btnxoanhanvien.setText("Xóa");
        btnxoanhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoanhanvienActionPerformed(evt);
            }
        });

        tblnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Họ Tên", "Mã NV", "Điện thoại", "Địa chỉ", "Chức Vụ", "Ghi chú"
            }
        ));
        jScrollPane2.setViewportView(tblnhanvien);

        lbltimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        lbltimkiem.setText("Tìm kiếm :");
        lbltimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbltimkiemMouseClicked(evt);
            }
        });

        btnhienhethong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        btnhienhethong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhienhethong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhienhethongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(btnthemnhanvien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsuanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxoanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltimkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnhienhethong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnthemnhanvien)
                            .addComponent(btnsuanhanvien)
                            .addComponent(btnxoanhanvien)
                            .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltimkiem)
                            .addComponent(btnhienhethong, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NhanVien.addTab("Nhân viên", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NhanVien)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ResultSet rs = QuyenBLL.LayTatCaQuyen();
         QuyenBLL.DoDuLieuVaoJTableQuyentrongBangNhanvien(rs,tblquyen);
         
         ResultSet rs1 = NhanVienBLL.LayTatCaNhanVien();
        NhanVienBLL.DoDuLieuVaoJTableQuyentrongBangNhanvien(rs1, tblnhanvien);
    }//GEN-LAST:event_formWindowOpened

    private void btnhienhethongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhienhethongActionPerformed
        ResultSet rs = NhanVienBLL.LayTatCaNhanVien();
        NhanVienBLL.DoDuLieuVaoJTableQuyentrongBangNhanvien(rs, tblnhanvien);
    }//GEN-LAST:event_btnhienhethongActionPerformed

    private void lbltimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltimkiemMouseClicked
        // TODO add your handling code here:
        String tuKhoa = txttimkiem.getText();
        //Kết quả của tìm theo từ khóa ResultSet
        ResultSet rs = NhanVienBLL.LayNVTheoTuKhoa(tuKhoa);
        //gọi hàm đổ dữ liệu sau khi tìm kiếm vào Table
        NhanVienBLL.DoDuLieuVaoJTableNhanVienDayDu(rs, tblnhanvien);
    }//GEN-LAST:event_lbltimkiemMouseClicked

    private void btnxoanhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoanhanvienActionPerformed
        // TODO add your handling code here:
        int cacViTriDuocChon = tblnhanvien.getSelectedRow();
        //Dùng vòng lặp để duyệt tất cả các phần tử trong mảng,
        //phần tử ở vị trí thứ i là cacViTriDuocChon[i]. Đây chính là vị trí dòng được chọn

        //Lấy mã loại trong Table LoaiSanPham
        //Hàm getValueAt(row, column): lấy giá trị tại dòng nào và cột nào
        int MaLoaiCanXoa = Integer.parseInt(tblnhanvien.getValueAt(cacViTriDuocChon, 1).toString());
        //Gọi hàm xóa ở tầng xử lý
        NhanVienBLL.XoaNhanVien(MaLoaiCanXoa);

        ResultSet rs = NhanVienBLL.LayTatCaNhanVien();
        //Đọc lại dữ liệu và đổ lại dữ liệu
        NhanVienBLL.DoDuLieuVaoJTableQuyentrongBangNhanvien(rs, tblnhanvien);
    }//GEN-LAST:event_btnxoanhanvienActionPerformed

    private void btnsuanhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuanhanvienActionPerformed
        // TODO add your handling code here:
        FrmSuaNhanvien frm = new FrmSuaNhanvien();
        frm.show();
    }//GEN-LAST:event_btnsuanhanvienActionPerformed

    private void btnthemnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemnhanvienActionPerformed
        // TODO add your handling code here:
        FrmThemNHanvien frm = new FrmThemNHanvien();
        frm.show();
        ResultSet rs = NhanVienBLL.LayTatCaNhanVien();
        NhanVienBLL.DoDuLieuVaoJTableQuyentrongBangNhanvien(rs, tblnhanvien);
    }//GEN-LAST:event_btnthemnhanvienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane NhanVien;
    private javax.swing.JButton btnhienhethong;
    private javax.swing.JButton btnsuanhanvien;
    private javax.swing.JButton btnthemnhanvien;
    private javax.swing.JButton btnxoanhanvien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltimkiem;
    private javax.swing.JTable tblnhanvien;
    private javax.swing.JTable tblquyen;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
