/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormNho;

import BLL.ComboboxBLL;
import BLL.HangHoaSPBLL;
import BLL.LoaiSanPhamBLL;
import DTO.HangHoaSPDTO;
import Presentation.FrmChinh;
import java.sql.ResultSet;

/**
 *
 * @author HOANG
 */
public class FrmSuaHangHoa extends javax.swing.JFrame {

    /**
     * Creates new form FrmThemHangHoa
     */
    public FrmSuaHangHoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuaHanghoa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtidsanpham = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtngaynhap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtgianhap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtgiaban = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdonvitinh = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtHanBaohanh = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMota = new javax.swing.JTextField();
        btnluu = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        cbbsuahanghoa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblSuaHanghoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSuaHanghoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuaHanghoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSuaHanghoa);

        jLabel1.setText("ID Sản Phẩm:");

        txtidsanpham.setEditable(false);

        jLabel2.setText("Mã Loại:");

        jLabel3.setText("Tên SP:");

        jLabel4.setText("Email:");

        jLabel5.setText("Ngày Nhập:");

        jLabel6.setText("Giá Nhập:");

        jLabel8.setText("Số Lượng:");

        jLabel9.setText("Giá Bán:");

        jLabel10.setText("Đơn vị tính:");

        jLabel11.setText("Hạn Bảo Hành:");

        jLabel12.setText("Mô Tả:");

        btnluu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btnluu.setText("Lưu");
        btnluu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnluuMouseClicked(evt);
            }
        });
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thoat.png"))); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        cbbsuahanghoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnluu)
                .addGap(18, 18, 18)
                .addComponent(btnthoat)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtgiaban, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(txtgianhap, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHanBaohanh))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, 0))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsoluong)
                            .addComponent(txtdonvitinh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(txtTenSanPham))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtidsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbsuahanghoa, 0, 405, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbbsuahanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtdonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtHanBaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnthoat)
                    .addComponent(btnluu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
          int IDSanPham = Integer.parseInt(txtidsanpham.getText());
        int MaLoaiSanPham = Integer.parseInt(ComboboxBLL.getSelectedItemID(cbbsuahanghoa));
        String TenSanPham = txtTenSanPham.getText();
        String Imei = txtemail.getText();
        String NgayNhap = txtngaynhap.getText();
        String GiaNhap = txtgianhap.getText();
        int soluong = Integer.parseInt(txtsoluong.getText());
        String GiaBan = txtgiaban.getText();
        String DonViTinh = txtdonvitinh.getText();
        String HanBaoHanh = txtHanBaohanh.getText();
        String MoTa = txtMota.getText();
        HangHoaSPDTO HH = new HangHoaSPDTO(IDSanPham, MaLoaiSanPham, TenSanPham, Imei, NgayNhap, GiaNhap, soluong, GiaBan, DonViTinh, HanBaoHanh, MoTa);
        HangHoaSPBLL.SuaDonhang(HH);
          ResultSet rs = HangHoaSPBLL.LayTatCaDonhang();
        HangHoaSPBLL.DoDuLieuVaoJTableSuasanpham(rs, tblSuaHanghoa);
    }//GEN-LAST:event_btnluuActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        FrmChinh frm = new FrmChinh();
        frm.show();
    }//GEN-LAST:event_btnthoatActionPerformed

    private void tblSuaHanghoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuaHanghoaMouseClicked
        // TODO add your handling code here:
         int Vitridongduocchon = tblSuaHanghoa.getSelectedRow();
        txtidsanpham.setText(tblSuaHanghoa.getValueAt(Vitridongduocchon, 0).toString());
          cbbsuahanghoa.setSelectedItem(tblSuaHanghoa.getValueAt(Vitridongduocchon, 1).toString());
          txtTenSanPham.setText(tblSuaHanghoa.getValueAt(Vitridongduocchon, 2).toString());
          txtemail.setText(tblSuaHanghoa.getValueAt(Vitridongduocchon, 3).toString());
          txtngaynhap.setText(tblSuaHanghoa.getValueAt(Vitridongduocchon, 4).toString());
          txtgianhap.setText(tblSuaHanghoa.getValueAt(Vitridongduocchon, 5).toString());
          txtsoluong.setText(tblSuaHanghoa.getValueAt(Vitridongduocchon, 6).toString());
          txtgiaban.setText(tblSuaHanghoa.getValueAt(Vitridongduocchon, 7).toString());
          txtdonvitinh.setText(tblSuaHanghoa.getValueAt(Vitridongduocchon, 8).toString());
          txtHanBaohanh.setText(tblSuaHanghoa.getValueAt(Vitridongduocchon, 9).toString());
    }//GEN-LAST:event_tblSuaHanghoaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
           HangHoaSPBLL.DoDuLieuVaoJTableSuasanpham(HangHoaSPBLL.LayTatCaDonhang(), tblSuaHanghoa);
           ResultSet rs = HangHoaSPBLL.LayTatCaDonhang();
           ComboboxBLL.LoadDuLieuCombobox(rs, cbbsuahanghoa, "TenSanPham", "IDSanPham");
    }//GEN-LAST:event_formWindowOpened

    private void btnluuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnluuMouseClicked
        // TODO add your handling code here:
        int IDSanPham = Integer.parseInt(txtidsanpham.getText());;
        int MaLoaiSanPham = Integer.parseInt(ComboboxBLL.getSelectedItemID(cbbsuahanghoa));
        String TenSanPham = txtTenSanPham.getText();
        String Imei = txtemail.getText();
        String NgayNhap = txtngaynhap.getText();
        String GiaNhap = txtgianhap.getText();
        int soluong = Integer.parseInt(txtsoluong.getText());
        String GiaBan = txtgiaban.getText();
        String DonViTinh = txtdonvitinh.getText();
        String HanBaoHanh = txtHanBaohanh.getText();
        String MoTa = txtMota.getText();
        HangHoaSPDTO HH = new HangHoaSPDTO(IDSanPham, MaLoaiSanPham, TenSanPham, Imei, NgayNhap, GiaNhap, soluong, GiaBan, DonViTinh, HanBaoHanh, MoTa);
        HangHoaSPBLL.SuaDonhang(HH);
        ResultSet rs = HangHoaSPBLL.LayTatCaDonhang();
        HangHoaSPBLL.DoDuLieuVaoJTableSuasanpham(rs, tblSuaHanghoa);
    }//GEN-LAST:event_btnluuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSuaHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSuaHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSuaHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSuaHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSuaHangHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnthoat;
    private javax.swing.JComboBox<String> cbbsuahanghoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSuaHanghoa;
    private javax.swing.JTextField txtHanBaohanh;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtdonvitinh;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtgianhap;
    private javax.swing.JTextField txtidsanpham;
    private javax.swing.JTextField txtngaynhap;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables
}
